language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

group: stable

os: linux

script:
  - make re
  - ./105torus 1 -1 0 6 -5 1 6
  - ./105torus 2 -1 0 6 -5 1 12
  - ./105torus 3 -1 0 6 -5 1 8
  - vendor/bin/phpunit --coverage-clover=coverage.xml

notifications:
  email: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

after_success:
  - bash <(curl -s https://codecov.io/bash)